In [1]:
import tensorflow as tf

In [3]:
ones= tf.ones([2, 3, 4])

In [ ]:
tf.concat([[[1,2,3]]])

In [7]:
num_classes = 10

sample_condition = tf.eye(num_classes)


In [8]:
sample_condition

<tf.Tensor: id=15, shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [9]:
sample_condition = tf.reshape(sample_condition, [-1, 1, 1, num_classes])

In [10]:
sample_condition

<tf.Tensor: id=17, shape=(10, 1, 1, 10), dtype=float32, numpy=
array([[[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]]], dtype=float32)>

In [ ]:
    self.conv1 = ConvTranspose(256, 3, padding='valid')


In [53]:
noise = tf.random.uniform([1000, 1, 1, 100], minval=-1.0, maxval=1.0)


In [16]:
import numpy as np

In [20]:
np.array([1,2]) * np.array([[[1],[3],[4]]])

array([[[1, 2],
        [3, 6],
        [4, 8]]])

In [21]:
np.array([[[1],[3],[4]]])

array([[[1],
        [3],
        [4]]])

In [37]:
conditions = [[[0, 0, 1, 0]]]

In [45]:
tmp = conditions * tf.ones([10, 28, 28, 4])

In [46]:
np.moveaxis(tmp, -1, 1)

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 

In [54]:
noise

<tf.Tensor: id=384, shape=(1000, 1, 1, 100), dtype=float32, numpy=
array([[[[ 0.98011374,  0.8697586 ,  0.6057093 , ...,  0.7465782 ,
          -0.01977181,  0.70196724]]],


       [[[-0.6386368 , -0.50322986, -0.33336282, ...,  0.06392956,
           0.46857905,  0.5929878 ]]],


       [[[-0.73056316,  0.97104645, -0.19931841, ..., -0.03120399,
           0.37753344,  0.6689954 ]]],


       ...,


       [[[-0.29784894,  0.2502582 , -0.48384356, ..., -0.14435863,
          -0.01262784,  0.435529  ]]],


       [[[-0.30958033, -0.31396842, -0.81096506, ..., -0.8000698 ,
           0.732106  ,  0.12993956]]],


       [[[ 0.35976052, -0.29958773, -0.06842494, ..., -0.41124964,
           0.1722858 , -0.89679503]]]], dtype=float32)>

In [58]:
tf.keras.layers.Conv2DTranspose(3, (40, 1), padding='valid')(noise)

<tf.Tensor: id=596, shape=(1000, 40, 1, 3), dtype=float32, numpy=
array([[[[-0.14839034,  0.36980352,  0.0187012 ]],

        [[-0.07730857, -0.06887604, -0.13827777]],

        [[ 0.21546775,  0.06078123, -0.09470253]],

        ...,

        [[-0.06071504, -0.08411242,  0.00168781]],

        [[ 0.04776815,  0.06795412,  0.14274487]],

        [[ 0.19062395, -0.23663913, -0.12865917]]],


       [[[-0.19875698, -0.0046892 , -0.01718564]],

        [[ 0.18600433,  0.04052604, -0.04641541]],

        [[ 0.11004006, -0.09478635,  0.07296923]],

        ...,

        [[ 0.08697693,  0.11815446, -0.07561521]],

        [[ 0.07537612, -0.21381089, -0.04396785]],

        [[ 0.12327848,  0.02239314, -0.11142733]]],


       [[[-0.20059724, -0.00802928, -0.17599882]],

        [[ 0.28761968,  0.22255245, -0.17070508]],

        [[-0.01872477, -0.2628619 ,  0.16576666]],

        ...,

        [[-0.11739347,  0.04077636, -0.12096652]],

        [[-0.07349163, -0.23970225,  0.10557022]],

    

In [59]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Train 데이터를 불러옵니다.
train = pd.read_csv('C:/Users/ufoio/Documents/AI/Semiconductor_dacon/train.csv')
# Test 데이터를 불러옵니다.
test = pd.read_csv('C:/Users/ufoio/Documents/AI/Semiconductor_dacon/test.csv')

In [60]:
layer_col = ['layer_1', 'layer_2', 'layer_3', 'layer_4']
light_col = set(train.columns) - set(['layer_1', 'layer_2', 'layer_3', 'layer_4'])

light_col = list(train.columns.drop(['layer_1', 'layer_2', 'layer_3', 'layer_4']))

light = train[light_col]#.drop(['0'], axis=1)
layer = train[layer_col]

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))